kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: k8s-node-evictor
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: k8s-node-evictor
    namespace: k8s-node-evictor
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: k8s-node-evictor
  rules:
    - apiGroups: [""]
      resources:
        - nodes
      verbs: ["get", "list", "watch", "delete", "deletecollection"]
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: k8s-node-evictor
  subjects:
    - kind: ServiceAccount
      name: k8s-node-evictor
      namespace: k8s-node-evictor
  roleRef:
    kind: ClusterRole
    name: k8s-node-evictor
    apiGroup: ""
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: k8s-node-evictor
    labels:
      app: k8s-node-evictor
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: k8s-node-evictor
    template:
      metadata:
        labels:
          app: k8s-node-evictor
      spec:
        serviceAccount: k8s-node-evictor
        containers:
          - name: k8s-node-evictor
            image: docker.io/jdartigalongue/k8s-node-evictor:latest
            env:
              - name: MAX_TIMEOUT
                value: "5m"
            imagePullPolicy: Always